version: "3.9"

services:
  backend:
    build:
      context: ./qualipro-backend
    container_name: qualipro-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - qualipro
    networks:
      - qualipro-net

  frontend:
    build: 
      context: ./qualipro-front
    container_name: qualipro-front
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - backend
    networks:
      - qualipro-net

  qualipro:
    image: mysql:8.0
    container_name: qualipro
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: qualipro_db
      MYSQL_USER: qualipro
      MYSQL_PASSWORD: qualipro_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - qualipro-net


volumes:
  db_data:

networks:
  qualipro-net:
    driver: bridge
